spring:
    datasource:
        primary:
            url: jdbc:h2:~/boottemplate
            username: sa
            password:
            driver-class-name: org.h2.Driver
            validation-query: SELECT 1
            test-on-borrow: true
        secondary:
            url: jdbc:mysql://localhost:3306/boottemplate?useUnicode=true&characterEncoding=utf-8
            username: boottemplate
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver
            validation-query: SELECT 1
            test-on-borrow: true
    jpa:
        database: H2
        show-sql: true
        generate-ddl: true
#        hibernate:
#            ddl-auto: update
#            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#            dialect: org.hibernate.dialect.H2Dialect
    data:
        rest:
            base-path: /api/v1
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    security:
        enable-csrf: true
management:
    security:
        enabled: false
server:
    port: 80
multipart:
    enabled: false
logging:
    level:
        cc.openscanner: DEBUG
        org.springframework.security.web.access: DEBUG
---
spring:
    profiles: prod
    security:
        enable-csrf: true
server:
    port: 9008
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto
# setx SPRING_PROFILES_ACTIVE dev
---
spring:
    profiles: dev
    security:
        enable-csrf: true
    thymeleaf:
      cache: false
      prefix: file:///f:/github/boot-template/src/main/resources/templates/


